---
functional:
  - В соревновании должны участвовать только 2 игрока
  - Игроки должны иметь возможность выбрать язык программирования для решение задачи
  - Игрокам должен быть доступен просмотр результатов запуска тестов в реальном времени
  - Игрокам должен быть доступен просмотр написания кода соперника в реальном времени
  - Игроки могут общаться между собой в чате
  - Игроки могут общаться со зрителями в чате
  - Первый из игроков, чей код удовлетворит тестам, должен победить
  - Игроки могут выбрать язык программирования -JavaScript
  - Игроки могут выбрать язык программирования -PHP
  - Игроки могут выбрать язык программирования -Python
  - Игроки могут выбрать язык программирования -Ruby
  - У всех языков программирования должна отображаться соответствующая версия
  - Игроки могут создавать игру самостоятельно
  - Созданная игра должна высвечиваться как "доступная для подключения" у других пользователей
  - Второй пользователь может присоединиться к игре нажав "connect to game"
  - После того, как соперник назначался, у обоих игроков одновременно начинается игра
  - На сайте должны отображаться рейтинги игроков
  - На сайте должны отображаться имена игроков
  - Не должна быть возможность копирования кода из окна редактора
  - Игроки могут сдаться в игре с помощью соответствующей кнопки в интерфейсе
  - У игроков всплывают сообщения о результате проверок
  - У игроков всплывают сообщения о выигрыше игрока
  - На сайте можно выбрать игру с другом
  - На сайте можно следить за игрой других игроков в реальном времени
  - На сайте должен отображаться  статус игры
  - На сайте должен отображаться уровень сложности задачи
  - Каждая игра должна иметь отдельный чат
  - У игроков неограниченное количество проверок своего решения
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть
  - Вылетевший из игры участник в любой момент игры, пока она не закончена, может переподключиться в игру
  - Когда оба игрока вышли, игра считается полностью законченной
  - Законченная игра должна удаляться из памяти

non-functional:
  - Исходный код проекта должен быть открытым 
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - На странице игры слева должен находиться свой редактор
  - На странице игры справа должен находиться редактор соперника
  - Наверху страницы игры должно находиться время игры
  - Ниже времени на страницы игры должна находиться задание
  - Сайт должен иметь расширение для браузера Chrome

implicit:
  - На сайте должна быть возможность зарегистрироваться
  - На сайте должна быть возможность авторизоваться
  - Пользователь может авторизоваться в системе через свой аккаунт Github
  - Пользователь может авторизоваться в системе через свой аккаунт Discord
  - Пользователь может отвязать аккаунт Github
  - Пользователь может отвязать аккаунт Discord
  - На сайте должны отображаться данные пользователя (имя, никнейм)
  - Пользователь может изменить свои данные
  - Пользователь может выбрать язык программирования в своем профиле
  - Пользователь может выбрать звук уведомления
  - Пользователь может настроить громкость звука уведомления
  - При авторизации есть возможность восстановить пароль
  - У игрока не должна быть возможность редактировать код соперника
  - У пользователей не должна быть возможность вносить изменения в задачи игры
  - Пользователь может выйти из авторизованного аккаунта